
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

upgrade:
    source: cdn
    interval: 168h
    auto: false
    notice: false
transient_prompt:
  background: transparent
  foreground: "#ffffff"
  template: "{{ .Shell }}> "
blocks:
    - type: prompt
      alignment: left
      segments:
        - template:  {{ .UserName }} on
          foreground: '#45F1C2'
          type: session
          style: plain
        - properties:
            folder_separator_icon: /
            style: full
          template: '  {{ .Path }} '
          foreground: '#0CA0D8'
          type: path
          style: plain
        - properties:
            fetch_upstream_icon: true
          template: '{{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
          foreground: '#14A5AE'
          powerline_symbol: 
          type: git
          style: plain
    - type: prompt
      alignment: left
      segments:
        - template: ' '
          foreground: '#cd5e42'
          type: root
          style: plain
        - template: '# '
          foreground: '#CD4277'
          type: text
          style: plain
      newline: true
version: 3
