[language-server.ruff]
command = "ruff"
args = ["server"]


[[language]]
name = "python"
language-servers = ["ruff", "pylsp", "ty"]
formatter = ["ruff"]

[language-server.ruff.config.settings]
line-length = 90
exclude = [".git", ".venv", "_pycache_", ".pyc", "dist", ".html"]

[language-server.ruff.config.settings.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "RUF", # ruff-specific rules
]
ignore = ["RUF012"]
fixable = ["ALL"]
unfixable = []
extend-select = ["E501"]

[language-server.ruff.config.settings.format]
quote-style = "double"

[language-server.ruff.config.settings.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
known-first-party = ["api", "users", "blackboard"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true


[[language]]
name = "hcl"
scope = "source.hcl"
file-types = ["tf", "tfvars", "tofu"]
roots = ["."]
language-servers = ["tofu-ls"]
formatter = { command = "tofu", args = ["fmt", "-"] }
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language-server.tofu-ls]
command = "/home/ubuntu/.local/bin/tofu-ls"
args = ["serve"]

[[grammar]]
name = "hcl"
source = { git = "https://github.com/tree-sitter/tree-sitter-hcl", rev = "3e1e5f73b9a07b8f2b2b0b9b8b2b0b9b8b2b0b9" }


